/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelsRouteImport } from './routes/travels'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as DriverAdminRouteImport } from './routes/driver/admin'
import { Route as DriverPartnerRouteImport } from './routes/driver/partner'
import { Route as TravelsIndexRouteImport } from './routes/travels/index'
import { Route as TravelsBookingsRouteImport } from './routes/travels/bookings'
import { Route as TravelsLoginRouteImport } from './routes/travels/login'
import { Route as TravelsRegisterRouteImport } from './routes/travels/register'
import { Route as TravelsRoutesRouteImport } from './routes/travels/routes'
import { Route as TravelsSearchRouteImport } from './routes/travels/search'
import { Route as TravelsAdminIndexRouteImport } from './routes/travels/admin.index'
import { Route as TravelsAdminBookingsRouteImport } from './routes/travels/admin.bookings'
import { Route as TravelsAdminDashboardRouteImport } from './routes/travels/admin.dashboard'
import { Route as TravelsAdminVehiclesRouteImport } from './routes/travels/admin.vehicles'
import { Route as TravelsBookVehicleIdRouteImport } from './routes/travels/book.$vehicleId'
import { Route as TravelsVehiclesIndexRouteImport } from './routes/travels/vehicles.index'
import { Route as TravelsVehiclesIdRouteImport } from './routes/travels/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelsRoute = TravelsRouteImport.update({
  id: '/travels',
  path: '/travels',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAdminRoute = DriverAdminRouteImport.update({
  id: '/driver/admin',
  path: '/driver/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPartnerRoute = DriverPartnerRouteImport.update({
  id: '/driver/partner',
  path: '/driver/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelsIndexRoute = TravelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsBookingsRoute = TravelsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsLoginRoute = TravelsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsRegisterRoute = TravelsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsRoutesRoute = TravelsRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsSearchRoute = TravelsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsAdminIndexRoute = TravelsAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsAdminBookingsRoute = TravelsAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsAdminDashboardRoute = TravelsAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsAdminVehiclesRoute = TravelsAdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsBookVehicleIdRoute = TravelsBookVehicleIdRouteImport.update({
  id: '/book/$vehicleId',
  path: '/book/$vehicleId',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsVehiclesIndexRoute = TravelsVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => TravelsRoute,
} as any)
const TravelsVehiclesIdRoute = TravelsVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => TravelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/travels': typeof TravelsRouteWithChildren
  '/driver/admin': typeof DriverAdminRoute
  '/driver/partner': typeof DriverPartnerRoute
  '/travels/bookings': typeof TravelsBookingsRoute
  '/travels/login': typeof TravelsLoginRoute
  '/travels/register': typeof TravelsRegisterRoute
  '/travels/routes': typeof TravelsRoutesRoute
  '/travels/search': typeof TravelsSearchRoute
  '/driver/': typeof DriverIndexRoute
  '/travels/': typeof TravelsIndexRoute
  '/travels/admin/bookings': typeof TravelsAdminBookingsRoute
  '/travels/admin/dashboard': typeof TravelsAdminDashboardRoute
  '/travels/admin/vehicles': typeof TravelsAdminVehiclesRoute
  '/travels/book/$vehicleId': typeof TravelsBookVehicleIdRoute
  '/travels/vehicles/$id': typeof TravelsVehiclesIdRoute
  '/travels/admin/': typeof TravelsAdminIndexRoute
  '/travels/vehicles/': typeof TravelsVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver/admin': typeof DriverAdminRoute
  '/driver/partner': typeof DriverPartnerRoute
  '/travels/bookings': typeof TravelsBookingsRoute
  '/travels/login': typeof TravelsLoginRoute
  '/travels/register': typeof TravelsRegisterRoute
  '/travels/routes': typeof TravelsRoutesRoute
  '/travels/search': typeof TravelsSearchRoute
  '/driver': typeof DriverIndexRoute
  '/travels': typeof TravelsIndexRoute
  '/travels/admin/bookings': typeof TravelsAdminBookingsRoute
  '/travels/admin/dashboard': typeof TravelsAdminDashboardRoute
  '/travels/admin/vehicles': typeof TravelsAdminVehiclesRoute
  '/travels/book/$vehicleId': typeof TravelsBookVehicleIdRoute
  '/travels/vehicles/$id': typeof TravelsVehiclesIdRoute
  '/travels/admin': typeof TravelsAdminIndexRoute
  '/travels/vehicles': typeof TravelsVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/travels': typeof TravelsRouteWithChildren
  '/driver/admin': typeof DriverAdminRoute
  '/driver/partner': typeof DriverPartnerRoute
  '/travels/bookings': typeof TravelsBookingsRoute
  '/travels/login': typeof TravelsLoginRoute
  '/travels/register': typeof TravelsRegisterRoute
  '/travels/routes': typeof TravelsRoutesRoute
  '/travels/search': typeof TravelsSearchRoute
  '/driver/': typeof DriverIndexRoute
  '/travels/': typeof TravelsIndexRoute
  '/travels/admin/bookings': typeof TravelsAdminBookingsRoute
  '/travels/admin/dashboard': typeof TravelsAdminDashboardRoute
  '/travels/admin/vehicles': typeof TravelsAdminVehiclesRoute
  '/travels/book/$vehicleId': typeof TravelsBookVehicleIdRoute
  '/travels/vehicles/$id': typeof TravelsVehiclesIdRoute
  '/travels/admin/': typeof TravelsAdminIndexRoute
  '/travels/vehicles/': typeof TravelsVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/travels'
    | '/driver/admin'
    | '/driver/partner'
    | '/travels/bookings'
    | '/travels/login'
    | '/travels/register'
    | '/travels/routes'
    | '/travels/search'
    | '/driver/'
    | '/travels/'
    | '/travels/admin/bookings'
    | '/travels/admin/dashboard'
    | '/travels/admin/vehicles'
    | '/travels/book/$vehicleId'
    | '/travels/vehicles/$id'
    | '/travels/admin/'
    | '/travels/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver/admin'
    | '/driver/partner'
    | '/travels/bookings'
    | '/travels/login'
    | '/travels/register'
    | '/travels/routes'
    | '/travels/search'
    | '/driver'
    | '/travels'
    | '/travels/admin/bookings'
    | '/travels/admin/dashboard'
    | '/travels/admin/vehicles'
    | '/travels/book/$vehicleId'
    | '/travels/vehicles/$id'
    | '/travels/admin'
    | '/travels/vehicles'
  id:
    | '__root__'
    | '/'
    | '/travels'
    | '/driver/admin'
    | '/driver/partner'
    | '/travels/bookings'
    | '/travels/login'
    | '/travels/register'
    | '/travels/routes'
    | '/travels/search'
    | '/driver/'
    | '/travels/'
    | '/travels/admin/bookings'
    | '/travels/admin/dashboard'
    | '/travels/admin/vehicles'
    | '/travels/book/$vehicleId'
    | '/travels/vehicles/$id'
    | '/travels/admin/'
    | '/travels/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TravelsRoute: typeof TravelsRouteWithChildren
  DriverAdminRoute: typeof DriverAdminRoute
  DriverPartnerRoute: typeof DriverPartnerRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travels': {
      id: '/travels'
      path: '/travels'
      fullPath: '/travels'
      preLoaderRoute: typeof TravelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/admin': {
      id: '/driver/admin'
      path: '/driver/admin'
      fullPath: '/driver/admin'
      preLoaderRoute: typeof DriverAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/partner': {
      id: '/driver/partner'
      path: '/driver/partner'
      fullPath: '/driver/partner'
      preLoaderRoute: typeof DriverPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travels/': {
      id: '/travels/'
      path: '/'
      fullPath: '/travels/'
      preLoaderRoute: typeof TravelsIndexRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/bookings': {
      id: '/travels/bookings'
      path: '/bookings'
      fullPath: '/travels/bookings'
      preLoaderRoute: typeof TravelsBookingsRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/login': {
      id: '/travels/login'
      path: '/login'
      fullPath: '/travels/login'
      preLoaderRoute: typeof TravelsLoginRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/register': {
      id: '/travels/register'
      path: '/register'
      fullPath: '/travels/register'
      preLoaderRoute: typeof TravelsRegisterRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/routes': {
      id: '/travels/routes'
      path: '/routes'
      fullPath: '/travels/routes'
      preLoaderRoute: typeof TravelsRoutesRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/search': {
      id: '/travels/search'
      path: '/search'
      fullPath: '/travels/search'
      preLoaderRoute: typeof TravelsSearchRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/admin/': {
      id: '/travels/admin/'
      path: '/admin'
      fullPath: '/travels/admin/'
      preLoaderRoute: typeof TravelsAdminIndexRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/admin/bookings': {
      id: '/travels/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/travels/admin/bookings'
      preLoaderRoute: typeof TravelsAdminBookingsRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/admin/dashboard': {
      id: '/travels/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/travels/admin/dashboard'
      preLoaderRoute: typeof TravelsAdminDashboardRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/admin/vehicles': {
      id: '/travels/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/travels/admin/vehicles'
      preLoaderRoute: typeof TravelsAdminVehiclesRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/book/$vehicleId': {
      id: '/travels/book/$vehicleId'
      path: '/book/$vehicleId'
      fullPath: '/travels/book/$vehicleId'
      preLoaderRoute: typeof TravelsBookVehicleIdRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/vehicles/': {
      id: '/travels/vehicles/'
      path: '/vehicles'
      fullPath: '/travels/vehicles/'
      preLoaderRoute: typeof TravelsVehiclesIndexRouteImport
      parentRoute: typeof TravelsRoute
    }
    '/travels/vehicles/$id': {
      id: '/travels/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/travels/vehicles/$id'
      preLoaderRoute: typeof TravelsVehiclesIdRouteImport
      parentRoute: typeof TravelsRoute
    }
  }
}

interface TravelsRouteChildren {
  TravelsBookingsRoute: typeof TravelsBookingsRoute
  TravelsLoginRoute: typeof TravelsLoginRoute
  TravelsRegisterRoute: typeof TravelsRegisterRoute
  TravelsRoutesRoute: typeof TravelsRoutesRoute
  TravelsSearchRoute: typeof TravelsSearchRoute
  TravelsIndexRoute: typeof TravelsIndexRoute
  TravelsAdminBookingsRoute: typeof TravelsAdminBookingsRoute
  TravelsAdminDashboardRoute: typeof TravelsAdminDashboardRoute
  TravelsAdminVehiclesRoute: typeof TravelsAdminVehiclesRoute
  TravelsBookVehicleIdRoute: typeof TravelsBookVehicleIdRoute
  TravelsVehiclesIdRoute: typeof TravelsVehiclesIdRoute
  TravelsAdminIndexRoute: typeof TravelsAdminIndexRoute
  TravelsVehiclesIndexRoute: typeof TravelsVehiclesIndexRoute
}

const TravelsRouteChildren: TravelsRouteChildren = {
  TravelsBookingsRoute: TravelsBookingsRoute,
  TravelsLoginRoute: TravelsLoginRoute,
  TravelsRegisterRoute: TravelsRegisterRoute,
  TravelsRoutesRoute: TravelsRoutesRoute,
  TravelsSearchRoute: TravelsSearchRoute,
  TravelsIndexRoute: TravelsIndexRoute,
  TravelsAdminBookingsRoute: TravelsAdminBookingsRoute,
  TravelsAdminDashboardRoute: TravelsAdminDashboardRoute,
  TravelsAdminVehiclesRoute: TravelsAdminVehiclesRoute,
  TravelsBookVehicleIdRoute: TravelsBookVehicleIdRoute,
  TravelsVehiclesIdRoute: TravelsVehiclesIdRoute,
  TravelsAdminIndexRoute: TravelsAdminIndexRoute,
  TravelsVehiclesIndexRoute: TravelsVehiclesIndexRoute,
}

const TravelsRouteWithChildren =
  TravelsRoute._addFileChildren(TravelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TravelsRoute: TravelsRouteWithChildren,
  DriverAdminRoute: DriverAdminRoute,
  DriverPartnerRoute: DriverPartnerRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
