"""add created_by to drivers and customers

Revision ID: d736186bfe52
Revises: 49c6154e2300
Create Date: 2026-09-14 11:42:39.981049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd736186bfe52'
down_revision: Union[str, None] = '49c6154e2300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


created_by_enum = sa.Enum('self_signup', 'admin', name='created_by')


def upgrade() -> None:
    # Alembic does not auto-create a named enum on add_column — do it here so
    # the type exists before either ALTER TABLE references it.
    created_by_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('customers', sa.Column('created_by', created_by_enum, server_default='self_signup', nullable=False))
    op.add_column('drivers', sa.Column('created_by', created_by_enum, server_default='self_signup', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'created_by')
    op.drop_column('customers', 'created_by')
    created_by_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
